- name: Launch Route 53 record set
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-r53-recordset-{{ stack_identifier }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/Route53RecordSet.yml"
   template_parameters:
     HostedZoneName: "{{ HostedZoneName }}"
     HostedZoneId: "{{ HostedZoneId }}"
     TimeToLive: "{{ TimeToLive }}"
     Type: "{{ Type }}"
     RecordName: "{{ RecordName }}"
     ResourceRecord: "{{ ResourceRecord }}"
     AliasTarget: "{{ AliasTarget }}"
          
   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-r53-recordset"
     Description: "{{ ansible_user_id }} r53-recordset {{ ApplicationName }}"
  register: r53
