- name: Deploy r53 record set to openshift
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no

  - role: ansibleplaybookbundle.asb-modules

  - role: provision-r53-recordset-apb-openshift
