- name: include plan vars
  include_vars:
    file: "{{ _apb_plan_id }}.yml"
- name: generate b62 hash
  shell: "16to62 {{ params_hash }}"
  register: command_output
- name: set fact
  set_fact:
    stack_suffix: "{{ command_output.stdout }}"

- set_fact: plan_tasks_filename="hosted_zone.yml"
  when: _apb_plan_id == "r53-hostedzone"

- set_fact: plan_tasks_filename="record_set.yml"
  when: _apb_plan_id == "r53-recordset"

- name: "Loading tasks for plan: {{ _apb_plan_id }}"
  include: "{{ plan_tasks_filename }}"
