AWSTemplateFormatVersion: 2010-09-09
Description: 'This template creates a Route 53 hosted Zone. qs-1nt0fs92n'
Parameters:
  HostedZoneName:
    Description: Name of the hosted zone
    Type: String
Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref HostedZoneName
Outputs:
  HostedZoneId:
    Description: The Hosted Zone
    Value: !Ref HostedZone
