#############################################################################
# Deprovision Route 53 Record set topic
#############################################################################

- name: Remove Route 53 record set topic
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "apb-r53-recordset-{{ stack_identifier }}"
    state: "absent"
    region: "{{ region }}"
