- name: r53-hostedzone deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: deprovision-r53-hostedzone-apb-openshift
    playbook_debug: false