#############################################################################
# Deprovision Route 53 Hosted zone
#############################################################################

- name: Remove Route 53 Hosted Zone
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "apb-r53-hostedzone-{{ stack_identifier }}"
    state: "absent"
    region: "{{ region }}"
